export enum ErrorCode {
  LOGIN_ERROR = "LOGIN_ERROR",
  INVALID_PARAM = "INVALID_PARAM",
  REGISTER_ERROR = "SIGNUP_ERROR",
  PROFILE_ERROR = "PROFILE_GET_ERROR",
  CATEGORY_GET_ERROR = "CATEGORY_GET_ERROR",
  COURSE_BY_CATEGORY_GET_ERROR = "COURSE_BY_CATEGORY_GET_ERROR",
  COURSE_GET_ERROR = "COURSE_GET_ERROR",
  CHAPTER_GET_ERROR = "CHAPTER_GET_ERROR",
  LESSON_GET_ERROR = "LESSON_GET_ERROR",
  QUIZ_GET_ERROR = "QUIZ_GET_ERROR",
  QUE_GET_ERROR = "QUE_GET_ERROR",
  MEDIA_GET_ERROR = "MEDIA_GET_ERROR",
  PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR",
  INVALID_AUTH = "INVALID_AUTH",
  APP_TOKEN_ERROR = "SERVICE_TOKEN_ERROR",
  INVALID_TOKEN = "INVALID_TOKEN",
  ALREADY_EXIST = "ALREADY_EXIST",
}

export enum ErrorMessage {
  INVALID_PARAM = "Invalid parameter(s)",
  UNAUTHORIZED = "UNAUTHORIZED",
}
